adb push centernet_hourglass.rknn /userdata/rknn_inference_demo/
adb push centernet_mbv2.rknn /userdata/rknn_inference_demo/
adb push centernet_res50.rknn /userdata/rknn_inference_demo/
adb push mnasnet1_0.rknn /userdata/rknn_inference_demo/
adb push mobilenet_v2.rknn /userdata/rknn_inference_demo/
adb push resnet18.rknn /userdata/rknn_inference_demo/
adb push resnet50.rknn /userdata/rknn_inference_demo/
adb push squeezenet1_0.rknn /userdata/rknn_inference_demo/
adb push wide_resnet50_2.rknn /userdata/rknn_inference_demo/
